### ISSUE TITLE
add support for private repo's

### ISSUE THREAD

**Issue by smeijer** [neyric/gh-issues-gantt#20]
Doesn't work for private repos a.t.m. These repo's need a token in the `api url`, as you'll get a `NOT FOUND` reponse otherwise.

**Comment by ijstokes** [comment]
Works for me.  We have Git Hub Enterprise.  I did have to modify one of the JS files to add in a `config.api_endpoint` reference.  My `config.js` file:

```
   github: {
      api_endpoint: 'https://git.example.com/api/v3/repos/',
      repo: 'PRIVATEORG/PRIVATEREPOO',
      username: 'USERNAME',
      password: 'TOKEN_JUST_FOR_GANTT_TOOL'
   },
```

And here is the diff on `github.js`:

```
diff --git a/github.js b/github.js
index 75528f0..e5950e1 100644
--- a/github.js
+++ b/github.js
@@ -2,7 +2,7 @@ var request = require('request');

 module.exports = function(config) {

-   var baseUrl = "https://api.github.com/repos/" + config.repo;
+   var baseUrl = config.api_endpoint + config.repo;
```

**Comment by shauvik** [comment]
works for me. Your user in `config.js` needs to have access to the private repo.

**Comment by smeijer** [comment]
Thanks. My bad indeed.
