### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by laughedelic** [neyric/gh-issues-gantt#6]
What I did (taking into account #4):
- cloned
- `npm install`
- set username/password in `config.js` and the repo name 
- added the part of config from `public/config.js` (is it neccessary or optional?) — tried without it as well
- opened `http://localhost:3001/` and see this:
  ![screen shot 2014-04-21 at 1 40 14](https://cloud.githubusercontent.com/assets/766656/2751712/2de40d20-c8e5-11e3-935f-2672e12ce98d.png)

Nothing happens. Refresh doesn't help. In the terminal I see

```
 » node server.js                                                                                                                                                        01:39:45
Listening on port 3001
https://api.github.com/repos/laughedelic/gtm/issues?per_page=100&status=open&direction=asc
```

What am I doing wrong?

P.S. Just in case if it helps: Chrome version is `34.0.1847.116`

**Comment by mdietze** [comment]
I'm getting the exact same error as is listed above, but as far as I can tell my config files are set up as per the example:
```
module.exports = {
   username: 'mdietze',
   password: 'XXXXX',
   repo: 'PecanProject/pecan',
   port: 3001
};
```

```
var config = {
   repo: 'PecanProject/pecan',
   weekDaysOff: [0,6],
   colorByDev: {
      "mdietze": "ganttBlue",
      "unassigned": "ganttRed"
   },
   holidays: {},
   excludedMilestones: [],
   defaultDuration: 1 // in days
};
```

Furthermore, I can see a link showing up at the command line when I hit the Refresh button, and that returns files that have our issues: 
https://api.github.com/repos/PecanProject/pecan/issues?per_page=100&status=open&direction=asc
https://api.github.com/repositories/6857384/issues?per_page=100&status=open&direction=asc&page=2

So at least part of the config is right. Any guesses what am I doing wrong?
